apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-deployment
  labels:
    name: provider-deployment
    env: prod
spec:
  template:
    metadata:
      name: provider-pod
      labels:
        name: provider-pod
    spec:
      containers:
        - name: provider-service
          image: lxfutbol/provider-service:dockerfile1      
      restartPolicy: Always
  replicas: 1
  selector:
    matchLabels:
      name: provider-pod

---

apiVersion: v1
kind: Service
metadata:
  name: provider-service
  labels:
    name: provider-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30004
  selector:
    name: provider-pod