apiVersion: v1
kind: Service
metadata:
  name: provider-service
  labels:
    name: provider-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30004
  selector:
    name: provider-pod