apiVersion: v1
kind: Service
metadata:
  name: zuul-service
  labels:
    name: zuul-service
spec:
  type: NodePort
  ports:
    - port: 8765
      targetPort: 8765
      nodePort: 30003
  selector:
    name: zuul-pod