version: '3.3'
services:
  zookeeper:
    image: 'wurstmeister/zookeeper'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - lxfutbol-compose-network

  kafka:
    image: 'wurstmeister/kafka'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:      
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092      
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper
    networks:
      - lxfutbol-compose-network      

  redis:
    image: "redis:alpine"  
    command: redis-server 
    ports:
      - "6379:6379"  
    volumes:
      - redis-data:/data
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - lxfutbol-compose-network   

  eureka-service:
    image: lxfutbol/eureka-microservice:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    restart: always
    networks:
      - lxfutbol-compose-network  

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_PASSWORD: lxfutbolPass 
      MYSQL_USER: lxfutbol
      MYSQL_PASSWORD: lxfutbolPass
      MYSQL_DATABASE: lxfutbol
      HOST_URL: localhost
    volumes:
      - mysql-database-volume:/var/lib/mysql
    networks:
      - lxfutbol-compose-network

  zuul-api-gateway-service:
    image: lxfutbol/zuul-microservice:0.0.1-SNAPSHOT
    ports:
      - "8765:8765"
    restart: always
    depends_on: 
      - eureka-service
    environment: 
      HOST_URL: localhost
    networks:
      - lxfutbol-compose-network

  provider-service:
    image: lxfutbol/provider-service:dockerfile1
    ports:
      - "8080:8080"
    restart: always
    depends_on: 
      - eureka-service          
      - mysql      
    environment: 
      HOST_URL: localhost
      RDS_HOSTNAME: mysql
      RDS_PORT: 3306
      RDS_DB_NAME: lxfutbol
      RDS_USERNAME: lxfutbol
      RDS_PASSWORD: lxfutbolPass
    networks:
      - lxfutbol-compose-network

  integrator-service:
    image: lxfutbol/integrator-service:dockerfile1
    ports:
      - "8081:8081"
    restart: always
    depends_on: 
      - eureka-service
      - mysql
      - provider-service
    environment: 
      HOST_URL: localhost
      RDS_HOSTNAME: mysql
      RDS_PORT: 3306
      RDS_DB_NAME: lxfutbol
      RDS_USERNAME: lxfutbol
      RDS_PASSWORD: lxfutbolPass
    networks:
      - lxfutbol-compose-network  

  spectacle-service:
    image: lxfutbol/spectacle-service:dockerfile1
    ports:
      - "8758:8758"
    restart: always
    depends_on: 
      - eureka-service
      - mysql
      - provider-service
    environment: 
      HOST_URL: localhost
      RDS_HOSTNAME: mysql
      RDS_PORT: 3306
      RDS_DB_NAME: lxfutbol
      RDS_USERNAME: lxfutbol
      RDS_PASSWORD: lxfutbolPass
    networks:
      - lxfutbol-compose-network

  transform-json-service:
    image: lxfutbol/transform-json-service:dockerfile1
    ports:
      - "8086:8086"
    restart: always
    depends_on: 
      - eureka-service
      - mysql
      - provider-service
    environment: 
      HOST_URL: localhost
      RDS_HOSTNAME: mysql
      RDS_PORT: 3306
      RDS_DB_NAME: lxfutbol
      RDS_USERNAME: lxfutbol
      RDS_PASSWORD: lxfutbolPass
    networks:
      - lxfutbol-compose-network                  

# Volumes
volumes:
  mysql-database-volume:
  redis-data:    
  zookeeper_data:
    driver: local  
  kafka_data:  
    driver: local       

networks:
  lxfutbol-compose-network: