version: '3.7'
services:
  eureka-service:
    image: lxfutbol/eureka-microservice:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    restart: always
    networks:
      - lxfutbol-compose-network  

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_PASSWORD: lxfutbolPass 
      MYSQL_USER: lxfutbol
      MYSQL_PASSWORD: lxfutbolPass
      MYSQL_DATABASE: lxfutbol
    volumes:
      - mysql-database-volume:/var/lib/mysql
    networks:
      - lxfutbol-compose-network  

  zuul-api-gateway-service:
    image: lxfutbol/zuul-microservice:0.0.1-SNAPSHOT
    ports:
      - "8765:8765"
    restart: always
    depends_on: 
      - eureka-service    
    networks:
      - lxfutbol-compose-network       

  provider-service:
    image: lxfutbol/provider-service:dockerfile1
    ports:
      - "8080:8080"
    restart: always
    depends_on: 
      - eureka-service          
      - mysql
      
    environment:
      RDS_HOSTNAME: mysql
      RDS_PORT: 3306
      RDS_DB_NAME: lxfutbol
      RDS_USERNAME: lxfutbol
      RDS_PASSWORD: lxfutbolPass
    networks:
      - lxfutbol-compose-network

  integrator-service:
    image: lxfutbol/integrator-service:dockerfile1
    ports:
      - "8081:8080"
    restart: always
    depends_on: 
      - eureka-service
      - mysql
      - provider-service
    environment:
      RDS_HOSTNAME: mysql
      RDS_PORT: 3306
      RDS_DB_NAME: lxfutbol
      RDS_USERNAME: lxfutbol
      RDS_PASSWORD: lxfutbolPass
    networks:
      - lxfutbol-compose-network      
  
# Volumes
volumes:
  mysql-database-volume:

networks:
  lxfutbol-compose-network: