apiVersion: v1
kind: Service
metadata:
  name: integrator-service
  labels:
    name: integrator-service
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30005
  selector:
    name: integrator-pod