apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  labels:
    name: eureka-service
spec:
  type: NodePort
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 30000
  selector:
    name: eureka-pod