apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    name: redis-service
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30001
  selector:
    name: redis-service