apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  labels:
    name: payment-deployment
    env: prod
spec:
  template:
    metadata:
      name: payment-pod
      labels:
        name: payment-pod
    spec:
      containers:
        - name: payment-container
          image: paymentservice:dockerfile1      
      restartPolicy: Always
  replicas: 1
  selector:
    matchLabels:
      name: payment-pod

---

apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    name: payment-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30012
  selector:
    name: payment-pod