apiVersion: v1
kind: Service
metadata:
  name: transform-json-service
  labels:
    name: transform-json-service
spec:
  type: NodePort
  ports:
    - port: 8086
      targetPort: 8086
      nodePort: 30007
  selector:
    name: transform-json-pod